# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: drat-deployment

jobs:
  drat-deployment:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PKG_NAME: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Checkout drat repo
        uses: actions/checkout@v2
        with:
          repository: hugheylab/drat
          path: drat

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      
      - name: Set environmental variables
        run: |
          cd ${PKG_NAME}
          Rscript \
            -e 'dsc = read.dcf("DESCRIPTION")' \
            -e 'cat(sprintf("PKG_VERSION=%s\n", dsc[,"Version"]))' \
            -e 'cat(sprintf("PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))'
            >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd ${PKG_NAME}
          Rscript \
            -e 'install.packages(c("devtools", "BiocManager"))' \
            -e 'repos = BiocManager::repositories("https://hugheylab.github.io/drat/")' \
            -e 'devtools::install_dev_deps(dependencies = TRUE, repos = repos, upgrade = TRUE)' \
            -e 'install.packages("covr")'

      - name: Build Package
        run: |
          cd ${PKG_NAME}
          R CMD build . --md5

      - run: ls
      - run: ls ${PKG_NAME}
      - run: ls drat
      - name: Clean install dependencies and build
        run: |
          cd drat
          FILE=src/contrib/${PKG_TARBALL}
          echo "File: $FILE."
          DEPLOYTARBALL=true
